def Generate(output_file, swagger_elements):
    output_file.write("components:\n")
    output_file.write("  schemas:\n")
    for element in swagger_elements:
        if element["body_request"] != {}:
            output_file.write("    " + element["model_definition"]+ ":\n")
            output_file.write("      type: 'object'\n")
            output_file.write("      required:  ['id', 'id1', 'id2', 'data1', 'data2', 'data3']\n")
            output_file.write("      properties:\n")
            output_file.write("        id:\n")
            output_file.write("          type: 'integer'\n")
            output_file.write("        id1:\n")
            output_file.write("          type: 'integer'\n")
            output_file.write("        id2:\n")
            output_file.write("          type: 'integer'\n")
            output_file.write("        data1:\n")
            output_file.write("          type: 'string'\n")
            output_file.write("        data2:\n")
            output_file.write("          type: 'string'\n")
            output_file.write("        data3:\n")
            output_file.write("          type: 'string'\n")
